[theme]
base = "light"
primaryColor = "#FF4B4B"  # Cor primária
backgroundColor = "#FFFFFF"  # Cor de fundo
secondaryBackgroundColor = "#F0F2F6"  # Cor secundária
textColor = "#31333F"  # Cor do texto